#pragma once
#ifdef XBOX_PROFILE

#define LEFT_STICK_X 
#define LEFT_STICK_Y
#define RIGHT_STICK_X
#define RIGHT_STICK_Y
#define STICK_RADIUS
#define STICK_TRACKING_RADIUS
#define DPAD_HORIZONTAL_LEFT_TOP_ANGLE_X
#define DPAD_HORIZONTAL_LEFT_TOP_ANGLE_Y
#define DPAD_VERTICAL_LEFT_TOP_ANGLE_X
#define DPAD_VERTICAL_LEFT_TOP_ANGLE_Y
#define BUTTON_A_X
#define BUTTON_A_Y
#define BUTTON_B_X
#define BUTTON_B_Y
#define BUTTON_X_X
#define BUTTON_X_Y
#define BUTTON_Y_X
#define BUTTON_Y_Y
#define BUTTON_START_X
#define BUTTON_START_Y
#define BUTTON_BACK_X
#define BUTTON_BACK_Y
#define BUTTON_RADIUS
#define BUTTON_LEFT_BUMPER_X
#define BUTTON_LEFT_BUMPER_Y
#define BUTTON_RIGHT_BUMPER_X
#define BUTTON_RIGHT_BUMPER_Y

#endif
#ifdef PS_PROFILE

#define CONTROLLER_WIDTH 1014
#define CONTROLLER_HEIGHT 650

#define LEFT_STICK_X 
#define LEFT_STICK_Y
#define RIGHT_STICK_X
#define RIGHT_STICK_Y
#define DPAD_HORIZONTAL_LEFT_TOP_ANGLE_X
#define DPAD_HORIZONTAL_LEFT_TOP_ANGLE_Y
#define DPAD_VERTICAL_LEFT_TOP_ANGLE_X
#define DPAD_VERTICAL_LEFT_TOP_ANGLE_Y
#define BUTTON_A_X
#define BUTTON_A_Y
#define BUTTON_B_X
#define BUTTON_B_Y
#define BUTTON_X_X
#define BUTTON_X_Y
#define BUTTON_Y_X
#define BUTTON_Y_Y
#define BUTTON_START_X
#define BUTTON_START_Y
#define BUTTON_BACK_X
#define BUTTON_BACK_Y
#define BUTTON_LEFT_BUMPER_X
#define BUTTON_LEFT_BUMPER_Y
#define BUTTON_RIGHT_BUMPER_X
#define BUTTON_RIGHT_BUMPER_Y

#endif