#pragma once
#ifndef PS_PROFILE
#define PS_PROFILE

#define CONTROLLER_WIDTH 1014
#define CONTROLLER_HEIGHT 650

#define BUTTON_RADIUS 32
#define STICK_RADIUS 64
#define STICK_POINT_RADIUS 16

#define DPAD_LENGTH 43 
#define DPAD_HEIGHT 51

#define BUMPER_LENGTH 134 
#define BUMPER_HEIGHT 15

#define BUTTON_START_BACK_RADIUS 16

#define TRIGGER_FRAME_LENGTH 44 
#define TRIGGER_FRAME_HEIGHT 144

#define LEFT_STICK_X 344
#define LEFT_STICK_Y 343
#define RIGHT_STICK_X 670
#define RIGHT_STICK_Y 343
#define DPAD_LEFT_LEFT_TOP_ANGLE_X 104
#define DPAD_LEFT_LEFT_TOP_ANGLE_Y 161
#define DPAD_RIGHT_RIGHT_TOP_ANGLE_X 273
#define DPAD_RIGHT_RIGHT_TOP_ANGLE_Y 161
#define DPAD_TOP_LEFT_TOP_ANGLE_X 163
#define DPAD_TOP_LEFT_TOP_ANGLE_Y 103
#define DPAD_BOTTOM_LEFT_BOTTOM_ANGLE_X 163
#define DPAD_BOTTOM_LEFT_BOTTOM_ANGLE_Y 269

#define DPAD_TRIANGLE_DELTA_X 23
#define DPAD_TRIANGLE_DELTA_Y1 20
#define DPAD_TRIANGLE_DELTA_Y2 33

#define BUTTON_A_X 828
#define BUTTON_A_Y 256
#define BUTTON_B_X 900
#define BUTTON_B_Y 184
#define BUTTON_X_X 756
#define BUTTON_X_Y 184
#define BUTTON_Y_X 828
#define BUTTON_Y_Y 112
#define BUTTON_START_PIVOT_1_X 694
#define BUTTON_START_PIVOT_1_Y 62
#define BUTTON_START_PIVOT_2_X 694
#define BUTTON_START_PIVOT_2_Y 90
#define BUTTON_BACK_PIVOT_1_X 320
#define BUTTON_BACK_PIVOT_1_Y 62
#define BUTTON_BACK_PIVOT_2_X 320
#define BUTTON_BACK_PIVOT_2_Y 90
#define BUTTON_LEFT_BUMPER_X 128
#define BUTTON_LEFT_BUMPER_Y 14
#define BUTTON_RIGHT_BUMPER_X 751
#define BUTTON_RIGHT_BUMPER_Y 14

#define TRIGGER_LEFT_FRAME_X 298
#define TRIGGER_LEFT_FRAME_Y 484
#define TRIGGER_RIGHT_FRAME_X 672
#define TRIGGER_RIGHT_FRAME_Y 484

#define BUMPER_LEFT_SEGMENT_X 196
#define BUMPER_LEFT_SEGMENT_Y 172
#define BUMPER_LEFT_SEGMENT_RADIUS 172
#define BUMPER_LEFT_SEGMENT_A1 66.5
#define BUMPER_LEFT_SEGMENT_A2 113.5

#define BUMPER_RIGHT_SEGMENT_X 818
#define BUMPER_RIGHT_SEGMENT_Y 172
#define BUMPER_RIGHT_SEGMENT_RADIUS 172
#define BUMPER_RIGHT_SEGMENT_A1 66.5
#define BUMPER_RIGHT_SEGMENT_A2 113.5

#endif