#pragma once
#ifdef XBOX_PROFILE

#define LEFT_STICK_X 
#define LEFT_STICK_Y
#define RIGHT_STICK_X
#define RIGHT_STICK_Y
#define STICK_RADIUS
#define STICK_TRACKING_RADIUS
#define DPAD_HORIZONTAL_LEFT_TOP_ANGLE_X
#define DPAD_HORIZONTAL_LEFT_TOP_ANGLE_Y
#define DPAD_VERTICAL_LEFT_TOP_ANGLE_X
#define DPAD_VERTICAL_LEFT_TOP_ANGLE_Y
#define BUTTON_A_X 
#define BUTTON_A_Y 
#define BUTTON_B_X
#define BUTTON_B_Y
#define BUTTON_X_X
#define BUTTON_X_Y
#define BUTTON_Y_X 
#define BUTTON_Y_Y 
#define BUTTON_START_X
#define BUTTON_START_Y
#define BUTTON_BACK_X
#define BUTTON_BACK_Y
#define BUTTON_RADIUS
#define BUTTON_LEFT_BUMPER_X
#define BUTTON_LEFT_BUMPER_Y
#define BUTTON_RIGHT_BUMPER_X
#define BUTTON_RIGHT_BUMPER_Y

#endif
#ifdef PS_PROFILE

#define CONTROLLER_WIDTH 1014
#define CONTROLLER_HEIGHT 650

#define BUTTON_RADIUS 32
#define STICK_RADIUS 64
#define STICK_POINT_RADIUS 16

#define DPAD_LENGTH 45 
#define DPAD_HEIGHT 51

#define LEFT_STICK_X 344
#define LEFT_STICK_Y 343
#define RIGHT_STICK_X 670
#define RIGHT_STICK_Y 343
#define DPAD_LEFT_LEFT_TOP_ANGLE_X 104
#define DPAD_LEFT_LEFT_TOP_ANGLE_Y 161
#define DPAD_RIGHT_RIGHT_TOP_ANGLE_X 273
#define DPAD_RIGHT_RIGHT_TOP_ANGLE_Y 161
#define DPAD_TOP_LEFT_TOP_ANGLE_X 162
#define DPAD_TOP_LEFT_TOP_ANGLE_Y 103
#define DPAD_BOTTOM_LEFT_BOTTOM_ANGLE_X 162
#define DPAD_BOTTOM_LEFT_BOTTOM_ANGLE_Y 269
#define BUTTON_A_X 828
#define BUTTON_A_Y 256
#define BUTTON_B_X 900
#define BUTTON_B_Y 184
#define BUTTON_X_X 756
#define BUTTON_X_Y 184
#define BUTTON_Y_X 828
#define BUTTON_Y_Y 112
#define BUTTON_START_X
#define BUTTON_START_Y
#define BUTTON_BACK_X
#define BUTTON_BACK_Y
#define BUTTON_LEFT_BUMPER_X
#define BUTTON_LEFT_BUMPER_Y
#define BUTTON_RIGHT_BUMPER_X
#define BUTTON_RIGHT_BUMPER_Y

#endif